### ISSUE TITLE
Disable Wi-Fi Sense

### ISSUE THREAD

**Issue by hahndorf** [hahndorf/Set-Privacy#1]
See: http://windows.wonderhowto.com/inspiration/everything-you-need-disable-windows-10-0163552/

I don't have a Windows 10 with Wi-Fi, so I can't do this,

**Comment by urras** [comment]
There are two registry values for Wifi Sense in HKCU:\SOFTWARE\Microsoft\WcmSvc\wifinetworkmanager\features, both of which should be set to 0 in both Balanced and Strong mode

**Comment by hahndorf** [comment]
I can only see them in:
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WcmSvc\wifinetworkmanager\features`
not in HKCU

I added code to change those two values but I can't test whether this actually disables WiFi sense.

I may not have a Windows 10 box with Wifi for the next few months.

**Comment by urras** [comment]
You're right, they were in HKEY. Also, I can confirm that the solution you implemented works, just tested it on my Win10 box.
