### ISSUE TITLE
Language depending line

### ISSUE THREAD

**Issue by sklaes** [hahndorf/Set-Privacy#13]
In line 451 the keyword BUILTIN is useed, but it is depending on the Language of Windows 10.

Line 451:
$rule = New-Object System.Security.AccessControl.RegistryAccessRule ("BUILTIN\$adminGroupName","FullControl","Allow")

this shuld work :
$rule = New-Object System.Security.AccessControl.RegistryAccessRule ("$env:hostname\$adminGroupName","FullControl","Allow")

**Comment by hahndorf** [comment]
@sklaes - Thanks, being German I should have remembered that BUILTIN is not universal. 
There is no `$env:hostname`, `$env:computername` is the one you were thinking of. But I just removed that whole first part, it works fine without it.

**Comment by sklaes** [comment]
@hahndorf  tested your latest version, works without any issues
