### ISSUE TITLE
Group Policy

### ISSUE THREAD

**Issue by Radder124** [hahndorf/Set-Privacy#15]
Is it possible to configure a GP within the script?
I'm thinking about disabling the Windows Automatic Update and OneDrive use on win 10 pro/enterprise.

**Comment by hahndorf** [comment]
@Radder124 - Many Group Poiicy settings are nothing else but registry values. As long as you know which ones they are, you can change them. 

In a domain environment it still makes more sense to use domain based group policies.

I like to have only privacy settings in this script.

Just make a copy of the script, remove the privacy settings and add your own stuff to it.
