### ISSUE TITLE
Add Set-Privacy to the PowerShell Gallery

### ISSUE THREAD

**Issue by mkropat** [hahndorf/Set-Privacy#19]
Have you considered adding `Set-Privacy.ps1` to the [PowerShell Gallery](https://www.powershellgallery.com/PSScript)?

It would make installing the script as easy as:

```
Install-Script Set-Privacy
```

Then the user doesn't have to worry about being in the right directory, or unblocking zip files or anything like that.

I've never tried adding a script to the gallery, [but the instructions look pretty easy](https://www.powershellgallery.com/packages/upload). However, I have recently published [a PowerShell module on there](https://www.powershellgallery.com/packages/MlkPwgen), so I'd be happy to answer any questions I can.

**Comment by hahndorf** [comment]
I added a PSScriptInfo block and published to the gallery, I already had an account, so it was very simple. I can not see it in the gallery yet.
