### ISSUE TITLE
I'm a total beginner (sorry in advance)

### ISSUE THREAD

**Issue by N00bProgrammer123** [hahndorf/Set-Privacy#35]
Hello everyone! If anyone could help me I would greatly appreciate it! So basically I have downloaded the code and unzipped it to my Desktop page. I want to be able to edit the code to change the privacy settings as it's something I have to regularly do at work and it's quite a tedious task. I'm trying to work the code but I have no clue how to work the programme.

If I want to change the settings in this programme do I have to change the $value    to which ever setting I want e.g  $disable   ?

So far I have tried "Function ImproveTyping([int]$value)"   and then changing the "$value" to "$disable" so that it will turn off that setting. However when I run the programme which I do in the unzipped folder that I unzipped and click "run with powershell" on the application. None of the settings that I have changed the $value seem to change at all. I have tried saving the programme and then refreshing the folder to get it to accept the new commands however I cannot get it to work in my favour.

Am I using the programme correctly by changing the $value commands via "Windows Powershell ISE"? I'm not sure how to work this sort of programme as I'm a total beginner. Any help would be much appreciated.

Thank You
-N00bProgrammer123

**Comment by hahndorf** [comment]
You need to provide parameters when using this script, don't use `Run with PowerShell`, open a PowerShell session. WinKey+R then type `powershell.exe`  now first type the path to the script, e.g. `C:\temp\Set-Privacy.ps1` followed by parameters for example:

     C:\temp\Set-Privacy.ps1  -Disable -Feature ImproveTyping

You can edit the script itself, but you need to now about PowerShell and how it works to do so.

**Comment by N00bProgrammer123** [comment]
Thank you for the reply. I appreciate you taking time out of your day to help out a beginner. I will try out these parameters.
